services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rwimoveis_app
    restart: always
    ports:
      - "3010:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgres://rwimoveis:Laranja2016@164.152.60.126:5432/rwimoveis
      SQL_HOST: 164.152.60.126
      SQL_PORT: 5432
      SQL_DB_NAME: rwimoveis
      SQL_USER: rwimoveis
      SQL_PASSWORD: Laranja2016
      ADMIN_USER: admin
      ADMIN_PASSWORD: "Rw2026!PainelSeguro"
